name: calico
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  audioplayers: ^3.0.1
  cloud_firestore: ^4.4.3
  easy_search_bar: ^2.4.2
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^13.0.0
  flutter_markdown: ^0.6.14
  flutter_native_splash: ^2.2.19
  flutter_phone_direct_caller: ^2.1.1
  get: ^4.6.5
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  googleapis: ^10.1.0
  googleapis_auth: ^1.4.0
  html: ^0.15.2
  http: ^0.13.5
  jumping_dot: ^0.0.4
  percent_indicator: ^4.2.3
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.1
  table_calendar: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/mood/
    - assets/images/nav/
    - assets/images/icon/
    - assets/dialog_flow_auth.json
    - .env
    - assets/images/article/
    - assets/images/category/

flutter_native_splash:
  background_image: assets/images/splash.png
  color: "#F0E8D5"
  android: true
  ios: true
